# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5afd6b279d1653027832589c86df2dab55cdcc9d1b89e64e14f1da3b2a4db61fab3cb61bcaf85ddcb89e90f60274a0b6fe3cd605015aa6c363c21a90500fca33

test:
  secret_key_base: 0a0c3281494c3764017ec063b9f0b9b0e402ac5c2b913a1983cc3aafeba9b752331fd3d11c87e677708589d3daf653708c3ba74eb6c88c4ef89dbc80e9f71c3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
